version: "3.8"
services:
  db:
    image: expense-bot-db:0.1.0
    build:
      context: .
      dockerfile: database/Dockerfile
      cache_from:
        - expense-bot-db:0.1.0
    container_name: expense-bot-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  bi:
    image: expense-bot-bi:0.1.0
    build:
      context: .
      dockerfile: superset/Dockerfile
      cache_from:
        - expense-bot-bi:0.1.0
    container_name: expense-bot-bi
    restart: always
    depends_on:
      - db
    environment:
      - SUPERSET_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SUPERSET_ADMIN_USERNAME
      - SUPERSET_ADMIN_PASSWORD
    ports:
      - "3000:8088"
    volumes:
      - superset-data:/app/superset_home
  bot:
    image: expense-bot:0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - expense-bot:0.3.0
    container_name: expense-bot-bot
    restart: always
    depends_on:
      - bi
    environment:
      - EXPENSE_BOT_TOKEN
      - EXPENSE_BOT_DB_CONNECTION_STRING
      - SUPERSET_ADMIN_USERNAME
      - SUPERSET_ADMIN_PASSWORD
      - SUPERSET_UI_URL

volumes:
  local_pgdata:
  superset-data:
