ARG SUPERSET_VERSION=5.0.0-py311
FROM apache/superset:${SUPERSET_VERSION} as base

USER root
RUN uv pip install psycopg2-binary \
    && rm -rf /app/superset_home/.cache/ms-playwright/chromium-1187 \
    && apt-get update && apt-get install -y  \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER superset

# Worker
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libgobject-2.0-0 \
    libnspr4 \
    libnss3 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libxext6 \
    libx11-6 \
    libxcb1 \
    libasound2 \
    libexpat1 \
    libatspi2.0-0 \
    libpangocairo-1.0-0 \
    libpango-1.0-0 \
    libcairo2 \
    libfontconfig1 \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash -u 1000 superset

WORKDIR /app
COPY --from=base /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=base /app /app

COPY --chown=superset superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py
ENV PLAYWRIGHT_BROWSERS_PATH=/app/superset_home/.cache/ms-playwright

USER superset

CMD ["/app/.venv/bin/celery", "--app=superset.tasks.celery_app:app", "worker", "--pool=prefork", "-O", "fair", "-c", "4"]
